name: ClearInventory
api: [1.0.0]
main: Martin77Epic\ClearInventory\Main
version: 0.1
load: POSTWORLD
author: Martin77Epic and paetti
description: ClearInventory Plugin by Martin77Epic and paetti.
# Plugin by Martin77Epic and paetti
commands:
 ci:
  description: Clear Mine Inv command
  usage: "/ci"
  permission: m77e.cim
 cim:
  description: Clear inv. from all
  usage: "/cia"
  permission: m77e.cia
permissions:
 m77e.cim:
  description: "Allows the user to run cim command"
  default: op
 m77e.cia:
  description: "Allows the user to run cia command"
  default: op
