name: ClearInventory
api: [1.0.0]
main: Martin77Epic\ClearInventory\Main
version: 0.1
load: POSTWORLD
author: "Martin77Epic, paetti"
description: ClearInventory Plugin by Martin77Epic and paetti
# Plugin by Martin77Epic and paetti
commands:
  cim:
    description: "Clear you Inventory"
      usage: "/cim."
  cia:
    description: "Clear Inventory from all!"
      usage: "/cia."
  cip:
    description: "Clear Inventory from a Player"
      usage: "/cip <player>."
#Permissons!
permissons:
  m77e.cim:
    default: op
  m77e.cia
    default: op
  m77e.cip
    default: op
